Fix activate_venv. Incompatible package selection broke InterOP

diff --git a/activate_venv b/activate_venv
--- a/activate_venv
+++ b/activate_venv
@@ -51,35 +51,43 @@ if [ -e ./_py3_venv/bin/activate ] ; then
 
     # MultiQc is under active development, so enable easy update
     if [ "${UPDATE_MULTIQC:-0}" != 0 ] ; then
-        pip3 install --upgrade pip
+        #pip3 install --upgrade pip
         install_multiqc upgrade
     fi
 
 else
     echo "Bootstrapping new VEnv from `which python3`"
-    ( set -e ; #)
-    python3 -mvenv ./_py3_venv
-    activate_venv
+    ( set -e ;
+        python3 -mvenv ./_py3_venv
+        activate_venv
 
-    pip3 install pip==19.2.1
-    pip3 install pyyaml==5.1.1
-    pip3 install yamlloader==0.5.5
-    pip3 install Rt==1.0.11
-    pip3 install pyclarity_lims==0.4.8
-    pip3 install psycopg2-binary==2.8.3
-    pip3 install pystache==0.5.4
+        pip3 install pip==19.2.1
+        pip3 install pyyaml==5.1.1
+        pip3 install yamlloader==0.5.5
+        pip3 install Rt==1.0.11
+        pip3 install pyclarity_lims==0.4.8
+        pip3 install psycopg2-binary==2.8.3
+        pip3 install pystache==0.5.4
 
-    # InterOP is now on PyPI so no pre-build needed :-)
-    pip3 install numpy==1.13.1
-    pip3 install interop==1.1.8
+        # InterOP is now on PyPI so no pre-build needed :-)
+        pip3 install numpy==1.16.4
+        pip3 install interop==1.1.8
 
-    # Needed if well_dups runs in the local VEnv, which it currently does.
-    pip3 install python-Levenshtein==0.12.0
+        # Needed if well_dups runs in the local VEnv, which it currently does.
+        pip3 install python-Levenshtein==0.12.0
 
-    # My own MultiQC and MultiQC_EdGen. Pip installs directly from GIT so
-    # why not? Assume the master branch is always good, since it's simpler than
-    # searching for the last release tag (though that is possible).
-    # see https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
-    install_multiqc
-    ) ; [ $? = 0 ] || echo "Provisioning VEnv Failed!"
+        # My own MultiQC and MultiQC_EdGen. Pip installs directly from GIT so
+        # why not? Assume the master branch is always good, since it's simpler than
+        # searching for the last release tag (though that is possible).
+        # see https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
+        install_multiqc
+    )
+
+    if [ $? = 0 ] ; then
+        # We need this since we quit the subshell
+        activate_venv
+    else
+        echo "Provisioning VEnv Failed!"
+        false
+    fi
 fi
