Add MultiQC to the Python VEnv and make it easier to configure.

diff --git a/activate_venv b/activate_venv
--- a/activate_venv
+++ b/activate_venv
@@ -3,9 +3,9 @@
 # Bootstrap a new VEnv in ./_py3_venv suitable for running Illuminatus.
 # This should probably be re-done as setup.py with proper deployment etc.
 # Just now we're running Illuminatus off the default python3 but a custom VEnv
-# seems much more sensible, not just for testing!
+# seems much more sensible, for production and testing!
 
-# After running this once, I can do, eg.:
+# After running this once in the workspace, I can do, eg.:
 # ( cd ../genologics && python3 ./setup.py develop )
 # and now I can tinker with the genologics code from my GIT checkout
 # without impacting the system shared Python.
@@ -19,6 +19,7 @@ if [ -e ./_py3_venv/bin/activate ] ; then
     source ./_py3_venv/bin/activate
 else
     echo "Bootstrapping new VEnv from `which python3`"
+    ( set -e ; #)
     python3 -mvenv ./_py3_venv
     source ./_py3_venv/bin/activate
 
@@ -26,4 +27,12 @@ else
     pip3 install Rt
     pip3 install genologics
     pip3 install psycopg2
+
+    # My own MultiQC and MultiQC_EdGen. Pip installs directly from GIT so
+    # why not? Assume the master branch is always good, since it's simpler than
+    # searching for the last release tag (though that is possible).
+    # see https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
+    pip3 install 'git+https://github.com/EdinburghGenomics/MultiQC.git#egg=multiqc'
+    pip3 install 'git+ssh://git@gitlab.genepool.private/production-team/MultiQC_EdGen.git#egg=multiqc_edgen'
+    ) ; [ $? = 0 ] || echo "Provisioning VEnv Failed!"
 fi
